import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@styles/globals.css'
import { AppParams, Locale } from '@types'
import { i18n } from '@constants'
import { GoogleTagManager } from '@next/third-parties/google'

const font = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const generateStaticParams = (): AppParams[] =>
  i18n.locales.map(locale => ({ locale }))

type RootLayoutProps = {
  children: React.ReactNode
  params?: AppParams
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const locale: Locale = params?.locale || i18n.defaultLocale

  return (
    <html lang={locale}>
      <body className={`${font.className} `}>{children}</body>
      <GoogleTagManager gtmId="GTM-TJKWVCJN" />
    </html>
  )
}
